<a href="https://colab.research.google.com/github/Alejohenao-8/python/blob/main/funtions_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Crear un diccionario con los datos
data = {
    'Nombre': ['Ana', 'Juan', 'Carlos', 'Laura', 'Miguel', 'Sofía', 'David', 'Carla'],
    'Profesión': ['Abogada', 'Ingeniero', 'Médico', 'Diseñadora', 'Profesor', 'Psicóloga', 'Arquitecto', 'Artista'],
    'País': ['España', 'México', 'Argentina', 'Colombia', 'Chile', 'Perú', 'Brasil', 'Uruguay']
}

# Crear el DataFrame
df = pd.DataFrame(data)

# Imprimir el DataFrame
print(df)

   Nombre   Profesión       País
0     Ana     Abogada     España
1    Juan   Ingeniero     México
2  Carlos      Médico  Argentina
3   Laura  Diseñadora   Colombia
4  Miguel    Profesor      Chile
5   Sofía   Psicóloga       Perú
6   David  Arquitecto     Brasil
7   Carla     Artista    Uruguay


In [1]:
from google.colab import files
import pandas as pd

# Subir archivo desde tu computadora
uploaded = files.upload()

# Cargar y mostrar las primeras 5 filas
df = pd.read_csv(next(iter(uploaded)))
print(df.head())

Saving Nombre.csv to Nombre.csv
   Nombre  Edad Departamento  Sueldo
0     Ana    29    Marketing    3000
1    Juan    34     Finanzas    3500
2  Carlos    45           TI    4000
3   Laura    29    Marketing    3100
4  Miguel    38     Finanzas    3600


In [2]:
import pandas as pd
import numpy as np

# Crear el DataFrame con valores aleatorios
df = pd.DataFrame(np.random.rand(100, 8), columns=[f'Col_{i+1}' for i in range(8)])

# Mostrar el DataFrame
print("Primeras filas del DataFrame:")
print(df.head())

# Mostrar el resumen estadístico
print("\nResumen estadístico del DataFrame:")
print(df.describe())

Primeras filas del DataFrame:
      Col_1     Col_2     Col_3     Col_4     Col_5     Col_6     Col_7  \
0  0.537767  0.293877  0.821715  0.957680  0.379176  0.026833  0.102536   
1  0.715160  0.093174  0.224810  0.546837  0.185512  0.118347  0.359653   
2  0.935300  0.197827  0.462768  0.966572  0.432880  0.995336  0.066520   
3  0.070449  0.931208  0.610444  0.841761  0.618538  0.220801  0.063737   
4  0.404471  0.999354  0.633429  0.476568  0.030074  0.778984  0.401259   

      Col_8  
0  0.540710  
1  0.962175  
2  0.136650  
3  0.140585  
4  0.263405  

Resumen estadístico del DataFrame:
            Col_1       Col_2       Col_3       Col_4       Col_5       Col_6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.507741    0.508156    0.525680    0.454292    0.530831    0.537800   
std      0.307226    0.288635    0.275652    0.278059    0.274648    0.311246   
min      0.000776    0.008756    0.010863    0.000186    0.003905    0.0003

In [3]:
import numpy as np

# Crear un array de números del 1 al 10
array = np.arange(1, 11)

# Calcular la suma, media y valor máximo
suma = np.sum(array)
media = np.mean(array)
valor_maximo = np.max(array)

# Mostrar los resultados
print("Array:", array)
print("Suma:", suma)
print("Media:", media)
print("Valor máximo:", valor_maximo)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Valor máximo: 10


In [4]:
import numpy as np

# Crear un array de 3x4 lleno de ceros
array = np.zeros((3, 4))
print("Array original (3x4):\n", array)

# Cambiar la forma del array a 2x6
array_reshaped = array.reshape(2, 6)
print("\nArray reshaped (2x6):\n", array_reshaped)

Array original (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array reshaped (2x6):
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
import numpy as np

# Generar una matriz aleatoria de 3x3
matriz = np.random.rand(3, 3)
print("Matriz aleatoria (3x3):\n", matriz)

# Calcular la transpuesta de la matriz
matriz_transpuesta = matriz.T
print("\nMatriz transpuesta:\n", matriz_transpuesta)

Matriz aleatoria (3x3):
 [[0.24735961 0.47487982 0.81341726]
 [0.15978261 0.79860412 0.41618197]
 [0.07147714 0.45033885 0.04182757]]

Matriz transpuesta:
 [[0.24735961 0.15978261 0.07147714]
 [0.47487982 0.79860412 0.45033885]
 [0.81341726 0.41618197 0.04182757]]
